import java.sql.*;

import static java.lang.Class.forName;

public class User {
    public static Connection con;
    public static Connection connectionz() throws Exception{
        Class.forName("com.mysql.cj.jdbc.Driver");
        con= DriverManager.getConnection("jdbc:mysql://localhost:3306/try","preeti","Darshun1310");
        return con;
    }
    public static int Register(RegisterAction ra){
        int flag=0;
        try{
            PreparedStatement pst=connectionz().prepareStatement("insert into try3(fname,lname,email,password) values(?,?,?,?)");
            //ResultSet tableKeys=pst.getGeneratedKeys();
            //int autoGeneratedID=tableKeys.getInt(1);
            //pst.setInt(1,autoGeneratedID);
            pst.setString(1,ra.getFname());
            pst.setString(2,ra.getLname());
            pst.setString(3,ra.getEmail());
            pst.setString(4,ra.getPassword());

            flag=pst.executeUpdate();
            //tableKeys = pst.getGeneratedKeys();
        } catch (SQLException e) {
            throw new RuntimeException(e);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
        return flag;
    }
}
